---
# tasks file for nginx-role

- name: Install Nginx
  package:
    name: "{{ nginx_packages[ansible_distribution] }}"
    state: present
  when: ansible_distribution in ['Ubuntu', 'CentOS']

- name: Include configuration template
  include_tasks: config.yml
  when: ansible_distribution in ['Ubuntu', 'CentOS']

- name: Configure Nginx
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
  notify: Restart Nginx
  tags: nginx

- name: Copy Nginx virtual host configuration
  template:
    src: nginx_vhost.conf.j2
    dest: /etc/nginx/sites-available/nginx.conf
  notify: Restart Nginx
  become: true

- name: Ensure Nginx service is running
  systemd:
    name: nginx
    state: started
    enabled: yes
  become: true

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded
  become: true

